apiVersion: v1
kind: Secret
metadata:
  name: subtracker-secrets
  namespace: subtracker
type: Opaque
data:
  # Backend secrets
  JWT_SECRET: "eW91cl9zdXBlcl9zZWNyZXRfa2V5X2NoYW5nZV9pbl9wcm9kdWN0aW9u"  # base64 encoded "your_super_secret_key_change_in_production"
  
  # Telegram Bot secrets
  TELEGRAM_BOT_TOKEN: "eW91cl9ib3RfdG9rZW5fZnJvbV9ib3RmYXRoZXI="  # base64 encoded "your_bot_token_from_botfather"
  
  # Database secrets
  DATABASE_USER: "c3VidHJhY2tlcl91c2Vy"  # base64 encoded "subtracker_user"
  DATABASE_PASSWORD: "c2VjdXJlX3Bhc3N3b3Jk"  # base64 encoded "secure_password"