apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: subtracker
  labels:
    app: telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
      - name: telegram-bot
        image: subtracker-telegram-bot:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        # Configuration from ConfigMap
        - name: BACKEND_API_URL
          valueFrom:
            configMapKeyRef:
              name: subtracker-config
              key: BACKEND_API_URL
        # Secrets from Secret
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: subtracker-secrets
              key: TELEGRAM_BOT_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: telegram-bot
  namespace: subtracker
  labels:
    app: telegram-bot
spec:
  selector:
    app: telegram-bot
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP