apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: subtracker
  labels:
    app: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
      - name: web-frontend
        image: subtracker/web-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        # Configuration from ConfigMap
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: subtracker-config
              key: VITE_API_BASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: subtracker
  labels:
    app: web-frontend
spec:
  selector:
    app: web-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP