/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSubscriptionRequest
 */
export interface CreateSubscriptionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    user_id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    billing_period: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    next_payment: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateSubscriptionRequest interface.
 */
export function instanceOfCreateSubscriptionRequest(value: object): value is CreateSubscriptionRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('billing_period' in value) || value['billing_period'] === undefined) return false;
    if (!('next_payment' in value) || value['next_payment'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function CreateSubscriptionRequestFromJSON(json: any): CreateSubscriptionRequest {
    return CreateSubscriptionRequestFromJSONTyped(json, false);
}

export function CreateSubscriptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscriptionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user_id': json['user_id'] == null ? undefined : json['user_id'],
        'name': json['name'],
        'price': json['price'],
        'currency': json['currency'],
        'billing_period': json['billing_period'],
        'next_payment': json['next_payment'],
        'category': json['category'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateSubscriptionRequestToJSON(json: any): CreateSubscriptionRequest {
    return CreateSubscriptionRequestToJSONTyped(json, false);
}

export function CreateSubscriptionRequestToJSONTyped(value?: CreateSubscriptionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['user_id'],
        'name': value['name'],
        'price': value['price'],
        'currency': value['currency'],
        'billing_period': value['billing_period'],
        'next_payment': value['next_payment'],
        'category': value['category'],
        'description': value['description'],
    };
}

