/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionResponse
 */
export interface SubscriptionResponse {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    user_id: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    billing_period: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    next_payment: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionResponse
     */
    is_active: boolean;
}

/**
 * Check if a given object implements the SubscriptionResponse interface.
 */
export function instanceOfSubscriptionResponse(value: object): value is SubscriptionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('billing_period' in value) || value['billing_period'] === undefined) return false;
    if (!('next_payment' in value) || value['next_payment'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('is_active' in value) || value['is_active'] === undefined) return false;
    return true;
}

export function SubscriptionResponseFromJSON(json: any): SubscriptionResponse {
    return SubscriptionResponseFromJSONTyped(json, false);
}

export function SubscriptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user_id': json['user_id'],
        'name': json['name'],
        'price': json['price'],
        'currency': json['currency'],
        'billing_period': json['billing_period'],
        'next_payment': json['next_payment'],
        'category': json['category'],
        'description': json['description'] == null ? undefined : json['description'],
        'is_active': json['is_active'],
    };
}

export function SubscriptionResponseToJSON(json: any): SubscriptionResponse {
    return SubscriptionResponseToJSONTyped(json, false);
}

export function SubscriptionResponseToJSONTyped(value?: SubscriptionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['user_id'],
        'name': value['name'],
        'price': value['price'],
        'currency': value['currency'],
        'billing_period': value['billing_period'],
        'next_payment': value['next_payment'],
        'category': value['category'],
        'description': value['description'],
        'is_active': value['is_active'],
    };
}

