name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.11'

jobs:
  # Сборка и тестирование проекта
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'

      - name: 🐍 Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 🧱 Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: web-frontend/package-lock.json

      - name: 🔧 Grant execute permission for mvnw
        run: |
          cd backend
          chmod +x mvnw

      - name: 🏗️ Build backend with Maven
        run: |
          cd backend
          ./mvnw clean package -DskipTests

      - name: 🧪 Run backend tests
        run: |
          cd backend
          ./mvnw test

      - name: 📦 Install frontend dependencies
        run: |
          cd web-frontend
          npm ci

      - name: 🎨 Lint frontend code
        run: |
          cd web-frontend
          npm run lint

      - name: 🧪 Run frontend tests
        run: |
          cd web-frontend
          npm test

      - name: 🏗️ Build frontend
        run: |
          cd web-frontend
          npm run build

      - name: 🐍 Install bot dependencies
        run: |
          cd telegram-bot
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: 🧪 Run bot tests
        run: |
          cd telegram-bot
          python -m pytest

      - name: 📊 Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: 'Test Results'
          path: |
            backend/target/surefire-reports/*.xml
            web-frontend/junit.xml
          reporter: java-junit

      - name: 📦 Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts
          path: |
            backend/target/*.jar
            web-frontend/.next/
            telegram-bot/dist/
          retention-days: 7

 # Проверка кода и безопасности
  code-quality:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'

      - name: 🔍 Run detekt (Kotlin linter)
        run: |
          cd backend
          ./mvnw detekt:check || true

      - name: 🔒 Run dependency vulnerability check
        run: |
          cd backend
          ./mvnw dependency-check:check || true

  # Сборка Docker образов (только для main ветки)
 docker-build:
    runs-on: ubuntu-latest
    needs: [build-and-test, code-quality]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 📦 Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/subtracker-backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: 🏗️ Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Интеграционные тесты с реальной базой данных
  integration-tests:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: subtracker_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'

      - name: 🔧 Grant execute permission for mvnw
        run: |
          cd backend
          chmod +x mvnw

      - name: 🧪 Run integration tests with PostgreSQL
        run: |
          cd backend
          ./mvnw verify -Dspring.profiles.active=test

      - name: 🌐 Test web frontend files
        run: |
          cd web-frontend
          npm ci
          npm run build
          npx serve -s out & 
          sleep 5
          curl -f http://localhost:3000/ || exit 1

  # Деплой (только для main ветки)
  deploy:
    runs-on: ubuntu-latest
    needs: [docker-build, integration-tests]
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
      - name: 🚀 Deploy to production server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Обновление Docker образов
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/subtracker-backend:latest
            
            # Остановка старых контейнеров
            docker stop subtracker-backend || true
            docker rm subtracker-backend || true
            
            # Создание бэкапа базы данных перед обновлением
            docker exec subtracker-backend cp /app/data/subtracker.db /app/data/subtracker.db.backup.$(date +%Y%m%d_%H%M%S) || true
            
            # Запуск нового контейнера
            docker run -d \
              --name subtracker-backend \
              --restart unless-stopped \
              -p 8080:8080 \
              -v /opt/subtracker/data:/app/data \
              -e DATABASE_URL="jdbc:sqlite:/app/data/subtracker.db" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              ${{ secrets.DOCKERHUB_USERNAME }}/subtracker-backend:latest
            
            # Проверка здоровья сервиса
            sleep 10
            curl -f http://localhost:8080/health || exit 1
            
            # Проверка API endpoints
            curl -f http://localhost:8080/login -X POST \
              -H "Content-Type: application/json" \
              -d '{"username":"user","password":"user"}' || exit 1
            
            # Мониторинг состояния приложения
            docker ps | grep subtracker-backend || exit 1
            
            # Проверка логов на наличие ошибок
            docker logs subtracker-backend 2>&1 | grep -i error || true

  # Уведомления о статусе деплоя
 notify:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always() && github.ref == 'refs/heads/main'
    
    steps:
      - name: 📧 Notify deployment status
        uses: 8398a7/action-slack@v3
        if: env.SLACK_WEBHOOK_URL != ''
        with:
          status: ${{ needs.deploy.result }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: 📋 Create release on success
        if: needs.deploy.result == 'success'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            🚀 Автоматический релиз из ветки main
            
            ## Изменения:
            - Commit: ${{ github.sha }}
            - Author: ${{ github.actor }}
            - Workflow: ${{ github.workflow }}
            
            ## Компоненты:
            - ✅ Backend API (SQLite/PostgreSQL)
            - ✅ Web Frontend (Next.js 15)
            - ✅ Telegram Bot (aiogram 3.22)
            
            ## Проверки:
            - ✅ Сборка и тесты
            - ✅ Проверка качества кода
            - ✅ Интеграционные тесты
            - ✅ Docker образы
            - ✅ Деплой в продакшен
          draft: false
          prerelease: false